# Generated by Django 3.2.6 on 2021-08-10 12:04

import apps.datatables.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=30, null=True, verbose_name='Last name')),
                ('phone', models.CharField(default='', max_length=30, null=True, verbose_name='Phone')),
                ('birth_date', models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('address', models.CharField(default='', max_length=200, null=True, verbose_name='Address')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('0', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=apps.datatables.models.upload_location)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['first_name'],
            },
        ),
    ]
