# Generated by Django 3.2.6 on 2021-09-19 13:29

import apps.datatables.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(default='', max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=30, null=True, verbose_name='Last name')),
                ('phone', models.CharField(default='', max_length=30, null=True, verbose_name='Phone')),
                ('birth_date', models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('address', models.CharField(default='', max_length=200, null=True, verbose_name='Address')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('0', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender')),
                ('profile_img', models.ImageField(blank=True, default='../media/profile_images/no-img.png', null=True, upload_to=apps.datatables.models.upload_location)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Technique', 'Technique'), ('Warning', 'Warning'), ('Graduation', 'Graduation')], default='', max_length=15)),
                ('created_on', models.DateField(blank='True', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('content', models.TextField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_since', models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Member since')),
                ('autorenew_membership', models.BooleanField(default=True)),
                ('membership_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PAUSED', 'PAUSED')], default='', max_length=8, verbose_name='Status')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='date activated')),
                ('activation_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('membership_type', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE')], default='', max_length=6, verbose_name='Type')),
                ('membership_period', models.CharField(choices=[('12 Months', '12 Months'), ('6 Months', '6 Months'), ('3 Months', '3 Months'), ('1 Month', '1 Month')], default='', max_length=10, verbose_name='Period')),
                ('membership', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('belt', models.CharField(choices=[('WHITE', 'WHITE'), ('BLUE', 'BLUE'), ('PURPLE', 'PURPLE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], default='', max_length=6)),
                ('stripe', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=1)),
                ('belt_since', models.DateField(blank='True', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Last Graduation')),
                ('graduation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.datatables.models.file_location, verbose_name='Document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
        ),
    ]
