# Generated by Django 3.2.6 on 2021-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
