# Generated by Django 3.2.6 on 2021-08-12 11:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(choices=[('WHITE', 'WHITE'), ('BLUE', 'BLUE'), ('PURPLE', 'PURPLE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], default='', max_length=6)),
                ('stripe', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=1)),
                ('belt_since', models.DateField(blank='True', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Last Graduation')),
                ('graduation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
        ),
    ]
