# Generated by Django 3.2.6 on 2021-08-13 15:22

import apps.datatables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0002_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, default='../media/profile_images/no-img.png', null=True, upload_to=apps.datatables.models.upload_location),
        ),
    ]
