# Generated by Django 3.2.7 on 2021-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
