# Generated by Django 3.2.7 on 2021-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0004_auto_20210926_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_period',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiry date'),
        ),
    ]
