# Generated by Django 3.2.6 on 2021-08-13 21:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0005_alter_student_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_category', models.CharField(choices=[('Technique', 'Technique'), ('Warning', 'Warning'), ('Graduation', 'Graduation')], default='', max_length=15)),
                ('posts_created_on', models.DateField(blank='True', null=True)),
                ('posts_content', models.TextField()),
                ('posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
            options={
                'ordering': ['posts_created_on'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Member since')),
                ('autorenew_membership', models.BooleanField(default=True)),
                ('membership_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PAUSED', 'PAUSED')], default='', max_length=8, verbose_name='Status')),
                ('activation_date', models.DateField(null=True, verbose_name='date activated')),
                ('membership_type', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE')], default='', max_length=6, verbose_name='Type')),
                ('membership_period', models.CharField(choices=[('12 Months', '12 Months'), ('6 Months', '6 Months'), ('3 Months', '3 Months')], default='', max_length=10, verbose_name='Period')),
                ('membership', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.student')),
            ],
        ),
    ]
