# Generated by Django 3.2.7 on 2021-10-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0005_auto_20211008_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
