# Generated by Django 3.2.6 on 2021-08-14 21:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0006_membership_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='posts_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='posts_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='posts_created_on',
        ),
        migrations.AddField(
            model_name='posts',
            name='created_on',
            field=models.DateField(blank='True', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='activation_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='date activated'),
        ),
    ]
