# Generated by Django 3.2.6 on 2021-08-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0007_auto_20210814_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posts',
            new_name='student',
        ),
    ]
