# Generated by Django 3.2.6 on 2021-08-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0008_rename_posts_posts_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='activation_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
