# Generated by Django 3.2.7 on 2021-10-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0008_auto_20211008_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='autorenew_membership',
            field=models.BooleanField(default=False),
        ),
    ]
