# Generated by Django 3.2.6 on 2021-08-16 11:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0009_membership_activation_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='activation_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='date activated'),
        ),
    ]
