# Generated by Django 3.2.6 on 2021-08-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0010_alter_membership_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='activation_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
