# Generated by Django 3.2.7 on 2021-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0010_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Guardian', 'Guardian'), ('Visitor', 'Visitor'), ('Student', 'Student'), ('Staff', 'Staff')], max_length=8, null=True, verbose_name='Your status'),
        ),
    ]
