# Generated by Django 3.2.7 on 2021-10-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0011_student_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
