# Generated by Django 3.2.6 on 2021-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0011_alter_membership_activation_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='date activated'),
        ),
    ]
