# Generated by Django 3.2.6 on 2021-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0012_alter_membership_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='activation_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_period',
            field=models.CharField(choices=[('12 Months', '12 Months'), ('6 Months', '6 Months'), ('3 Months', '3 Months'), ('1 Month', '1 Month')], default='', max_length=10, verbose_name='Period'),
        ),
    ]
