# Generated by Django 3.2.7 on 2021-10-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0013_student_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
