# Generated by Django 3.2.6 on 2021-08-19 11:40

import apps.datatables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0014_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.datatables.models.file_location, verbose_name='Document'),
        ),
    ]
