# Generated by Django 3.2.7 on 2021-10-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0014_document_upload_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_counter',
        ),
        migrations.AddField(
            model_name='student',
            name='upload_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
