# Generated by Django 3.2.7 on 2021-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0015_auto_20211017_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardians_name',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Guardians name (For all members under 18 years old)'),
        ),
    ]
