# Generated by Django 3.2.7 on 2021-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0017_rename_is_ready_student_is_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardians_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Guardians name (For all members under 18 years old)'),
        ),
    ]
