
[<Invoice invoice id=in_1JkXnRJJBXKsbxPkGoMNJXYI at 0x7f071c375860> JSON: {
  "account_country": "DE",
  "account_name": "BJJ DOJO BERLIN",
  "account_tax_ids": null,
  "amount_due": 100,
  "amount_paid": 100,
  "amount_remaining": 0,
  "application_fee_amount": null,
  "attempt_count": 1,
  "attempted": true,
  "auto_advance": false,
  "automatic_tax": {
    "enabled": false,
    "status": null
  },
  "billing_reason": "subscription_cycle",
  "charge": "py_3JkZ77JJBXKsbxPk0sKc1Ca9",
  "collection_method": "charge_automatically",
  "created": 1634232769,
  "currency": "eur",
  "custom_fields": null,
  "customer": "cus_KNracbZ2QLRHJc",
  "customer_address": null,
  "customer_email": "rodrigolfernandes@gmail.com",
  "customer_name": null,
  "customer_phone": null,
  "customer_shipping": null,
  "customer_tax_exempt": "none",
  "customer_tax_ids": [],
  "default_payment_method": null,
  "default_source": null,
  "default_tax_rates": [],
  "description": null,
  "discount": null,
  "discounts": [],
  "due_date": null,
  "ending_balance": 0,
  "footer": null,
  "hosted_invoice_url": "https://invoice.stripe.com/i/acct_1JR01OJJBXKsbxPk/test_YWNjdF8xSlIwMU9KSkJYS3NieFBrLF9LUE1XZExzYVMwd3k3UDgya2hQM0tOWkJQRWVVMjB60100ESFzrBUL",
  "id": "in_1JkXnRJJBXKsbxPkGoMNJXYI",
  "invoice_pdf": "https://pay.stripe.com/invoice/acct_1JR01OJJBXKsbxPk/test_YWNjdF8xSlIwMU9KSkJYS3NieFBrLF9LUE1XZExzYVMwd3k3UDgya2hQM0tOWkJQRWVVMjB60100ESFzrBUL/pdf",
  "last_finalization_error": null,
  "lines": {
    "data": [
      {
        "amount": 100,
        "currency": "eur",
        "description": "1 \u00d7 Dojo Test (at \u20ac1.00 / day)",
        "discount_amounts": [],
        "discountable": true,
        "discounts": [],
        "id": "il_1JkXnRJJBXKsbxPkvD5TIsmA",
        "livemode": false,
        "metadata": {},
        "object": "line_item",
        "period": {
          "end": 1634319062,
          "start": 1634232662
        },
        "plan": {
          "active": true,
          "aggregate_usage": null,
          "amount": 100,
          "amount_decimal": "100",
          "billing_scheme": "per_unit",
          "created": 1633877671,
          "currency": "eur",
          "id": "price_1Jj3Q3JJBXKsbxPkmiRc6Q2A",
          "interval": "day",
          "interval_count": 1,
          "livemode": false,
          "metadata": {},
          "nickname": null,
          "object": "plan",
          "product": "prod_KNp4sBRTQPZxQ1",
          "tiers_mode": null,
          "transform_usage": null,
          "trial_period_days": null,
          "usage_type": "licensed"
        },
        "price": {
          "active": true,
          "billing_scheme": "per_unit",
          "created": 1633877671,
          "currency": "eur",
          "id": "price_1Jj3Q3JJBXKsbxPkmiRc6Q2A",
          "livemode": false,
          "lookup_key": null,
          "metadata": {},
          "nickname": null,
          "object": "price",
          "product": "prod_KNp4sBRTQPZxQ1",
          "recurring": {
            "aggregate_usage": null,
            "interval": "day",
            "interval_count": 1,
            "trial_period_days": null,
            "usage_type": "licensed"
          },
          "tax_behavior": "inclusive",
          "tiers_mode": null,
          "transform_quantity": null,
          "type": "recurring",
          "unit_amount": 100,
          "unit_amount_decimal": "100"
        },
        "proration": false,
        "quantity": 1,
        "subscription": "sub_1Jj5rWJJBXKsbxPkqUC8Zwgj",
        "subscription_item": "si_KNragPLWnTyF5l",
        "tax_amounts": [],
        "tax_rates": [],
        "type": "subscription"
      }
    ],
    "has_more": false,
    "object": "list",
    "total_count": 1,
    "url": "/v1/invoices/in_1JkXnRJJBXKsbxPkGoMNJXYI/lines"
  },
  "livemode": false,
  "metadata": {},
  "next_payment_attempt": null,
  "number": "1F626D5B-0049",
  "object": "invoice",
  "on_behalf_of": null,
  "paid": true,
  "payment_intent": "pi_3JkZ77JJBXKsbxPk0ZvqPCWp",
  "payment_settings": {
    "payment_method_options": null,
    "payment_method_types": null
  },
  "period_end": 1634232662,
  "period_start": 1634146262,
  "post_payment_credit_notes_amount": 0,
  "pre_payment_credit_notes_amount": 0,
  "quote": null,
  "receipt_number": null,
  "starting_balance": 0,
  "statement_descriptor": null,
  "status": "paid",
  "status_transitions": {
    "finalized_at": 1634237833,
    "marked_uncollectible_at": null,
    "paid_at": 1634237839,
    "voided_at": null
  },
  "subscription": "sub_1Jj5rWJJBXKsbxPkqUC8Zwgj",
  "subtotal": 100,
  "tax": null,
  "total": 100,
  "total_discount_amounts": [],
  "total_tax_amounts": [],
  "transfer_data": null,
  "webhooks_delivered_at": 1634232769
}]
True
/v1/invoices



