# Generated by Django 3.2.6 on 2021-09-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatables', '0002_membership_qr_code'),
        ('attendance', '0002_remove_member_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestHash',
        ),
        migrations.AddField(
            model_name='member',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatables.membership'),
        ),
    ]
